
# 设为 "auto" 会自动检测(会有警告)，也可手动设定为 "cuda","mps","cpu","xpu" 其中之一。
[llm]
device = "auto"

[embed]
device = "cuda"

[reranker]
top_n = 20
#max_length = 1024
#model_path = ""
#batch_size = 32

[reranker.model]
"bge-reranker-large" = "/ai/models/BAAI_bge-reranker-large"
"bge-reranker-base" = "BAAI/bge-reranker-base"
bce-reranker-base_v1 = "G:/50-TEMP/models/embed/bce-reranker-base_v1"


[controller]
host = "0.0.0.0"
port = 21101
dispatch-method = "shortest_queue"

[worker]
host = "0.0.0.0"
port = 21002


[openai_api_server]
host = "0.0.0.0"
port = 8000
controller_address = "http://localhost:21101"
api_keys = "EMPTY"
